### PR TITLE
Issue 721

### PR DESCRIPTION
**Pull request by michaelhidalgo**
Merging customisations into Dev 
@luchia can you please take a look?

### CODE REVIEW

**Comment by DinisCruz** [comment]
same here, @luchia  please merge it if the changes are ok

**Comment by DinisCruz** [comment]
@michaelhidalgo should we have this Sony logo on the main repo https://github.com/TeamMentor/TM_Static/pull/10/files#diff-7bc4bacf03e492007aeea8376d739058 ?

**Comment by michaelhidalgo** [comment]
Good catch, we should not, I think it has to be on the respective repo.
I'll fix it.

2015-07-08 15:46 GMT-06:00 Dinis Cruz notifications@github.com:

> @michaelhidalgo https://github.com/michaelhidalgo should we have this
> Sony logo on the main repo
> https://github.com/TeamMentor/TM_Static/pull/10/files#diff-7bc4bacf03e492007aeea8376d739058
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TeamMentor/TM_Static/pull/10#issuecomment-119740574.

## 

Michael Hidalgo
http://michaelhidalgocr.blogspot.com

_The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer_

**Comment by michaelhidalgo** [comment]
https://github.com/michaelhidalgo/SiteData_sony.teammentor.net/blob/QA_Branch/TM/static/mixins/sony-mixin.jade#L7
I will do the change in there to pick up that tile image from the same
directory.

2015-07-08 17:26 GMT-06:00 Michael Hidalgo michaelfallas@gmail.com:

> Good catch, we should not, I think it has to be on the respective repo.
> I'll fix it.
> 
> 2015-07-08 15:46 GMT-06:00 Dinis Cruz notifications@github.com:
> 
> > @michaelhidalgo https://github.com/michaelhidalgo should we have this
> > Sony logo on the main repo
> > https://github.com/TeamMentor/TM_Static/pull/10/files#diff-7bc4bacf03e492007aeea8376d739058
> > ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/TeamMentor/TM_Static/pull/10#issuecomment-119740574.
> 
> ## 
> 
> Michael Hidalgo
> http://michaelhidalgocr.blogspot.com
> 
> _The future has many names: For the weak, it means the unattainable. For
> the fearful, it means the unknown. For the courageous, it means
> opportunity. (1802-1885) French Poet, Dramatist, Writer_

## 

Michael Hidalgo
http://michaelhidalgocr.blogspot.com

_The future has many names: For the weak, it means the unattainable. For
the fearful, it means the unknown. For the courageous, it means
opportunity. (1802-1885) French Poet, Dramatist, Writer_

**Pull request merged**
